Benjamin Wilson
Lab 5
October 4, 2021

Script started on 2021-10-04 09:44:59-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="192" LINES="11"]
]0;ben@Clover-VirtualBox: ~/cse113/lab5[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab5[00m$ gcc -g -Wall lab5_q3.c -o q3 -lm
]0;ben@Clover-VirtualBox: ~/cse113/lab5[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab5[00m$ ./q3
Enter (x, y) coordinates for point 1 as a decimal: (4.0, 5.0)
Enter (x, y) coordinates for point 2 as a decimal: (6.0, 2.0)

Euclidean Distance: 3.605551
Manhattan Distance: 5.000000

]0;ben@Clover-VirtualBox: ~/cse113/lab5[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab5[00m$ exit
exit

Script done on 2021-10-04 09:45:58-06:00 [COMMAND_EXIT_CODE="0"]
